import Link from 'next/link';
import {lifecycle} from '@/lib/lifecycle';
import {fmtDate} from '@/lib/utils';
export function DemandeProgress({demande:d,operations,canPlan}:{demande:any;operations:any[];canPlan:boolean}) {
 const s=lifecycle(d,operations);
 const steps=[['Demande','Coordinateur'],['Validation','Planning'],['Affectation','Planning'],['Réalisation','Équipe terrain'],['Retour terrain','Coordinateur']];
 return <section className="bg-paper border border-line rounded-xl mb-6 overflow-hidden" aria-label="Avancement de la demande"><ol className="grid grid-cols-1 sm:grid-cols-5 border-b border-line">{steps.map(([title,role],i)=><li key={title} aria-current={!s.stopped&&i===s.stage?'step':undefined} className={`px-4 py-4 border-b sm:border-b-0 sm:border-r last:border-0 border-line ${!s.stopped&&i===s.stage?'bg-ink text-white':''}`}><span className="text-xs opacity-70">{i+1} / {i<s.stage&&!s.stopped?'Étape passée':i===s.stage&&!s.stopped?(d.etat==='planifiee'?'À démarrer':'En cours'):'À venir'}</span><p className="font-semibold text-sm mt-1">{title}</p><p className="text-xs opacity-70 mt-1">{role}</p></li>)}</ol><div className="p-5"><p className="text-xs uppercase tracking-widest text-mute">{s.owner} · prochaine action</p><p className="font-medium mt-2">{s.action}</p>{canPlan&&(['acceptee','planifiee'].includes(d.etat)||(d.etat==='en_cours'&&s.assigned<s.total))&&<Link href={`/planning?date=${d.date_souhaitee??''}&demande=${d.id}`} className="inline-block bg-ink text-white rounded-lg px-4 py-2.5 text-sm mt-3">Affecter les moyens dans le planning →</Link>}<div className="grid sm:grid-cols-3 gap-3 mt-5 text-sm"><p><strong>{s.assigned}/{s.total}</strong> opérations affectées</p><p><strong>{s.done}/{s.total}</strong> opérations réalisées</p><a className="underline" href="#retours-terrain"><strong>{s.reports}/{s.total}</strong> comptes rendus disponibles</a></div>{s.returns>0&&<p className="border-t border-line pt-3 mt-4 text-sm">Transport retour : <strong>{s.returnsDone}/{s.returns}</strong> opérations réalisées{d.date_retour?` · prévu le ${fmtDate(d.date_retour)}`:''}. Il fait partie de la demande et doit aussi être exécuté.</p>}<p className="text-xs text-mute mt-3">« Terminée » signifie que les opérations sont clôturées. Les comptes rendus restent à vérifier ; cela ne vaut ni validation administrative ni facturation.</p></div></section>;
}
export function FieldReports({operations}:{operations:any[]}){
 const done=operations.filter(o=>o.etat==='terminee');
 return <section id="retours-terrain" className="scroll-mt-8 bg-paper border border-line rounded-xl p-5 mt-6"><h2 className="font-semibold text-xl">Retour du terrain</h2><p className="text-sm text-mute mt-1">Horaires, comptes rendus et réserves à relire par le coordinateur.</p>{!done.length?<p className="text-sm py-4">Les retours apparaîtront ici après la clôture des opérations.</p>:done.map(o=><article key={o.id} className="border-t border-line pt-4 mt-4"><h3 className="font-medium">{o.libelle??o.type_operation} {o.periode==='retour'?'· transport retour':''}</h3><p className="text-xs text-mute mt-1">{fmtDate(o.date_prevue)} · Arrivée : {o.heure_arrivee??'non renseignée'} · Départ : {o.heure_depart??'non renseigné'}</p><p className={`text-sm whitespace-pre-line mt-3 ${o.compte_rendu?'':'text-ochre'}`}>{o.compte_rendu?.trim()||'Compte rendu manquant : à demander à l’équipe.'}</p>{o.signature_nom&&<p className="text-xs mt-2">Nom saisi à la clôture : {o.signature_nom}</p>}</article>)}</section>;
}
