import {createClient} from '@/lib/supabase/server';
import {currentUser} from '@/lib/auth';
import {emailConfig} from '@/lib/email';
export async function EmailAlertsStatus(){
 const me=await currentUser();if(!me||!['admin','dispatcheur'].includes(me.role))return null;
 const db=await createClient();const {data,error}=await db.from('email_alerts').select('id,subject,status,created_at,last_error,recipient:utilisateurs!recipient_id(prenom,nom)').order('created_at',{ascending:false}).limit(20);
 const cfg=emailConfig();const enabled=process.env.EMAIL_ALERTS_ENABLED==='true' && !!cfg.key && !!process.env.ALERTS_FROM_EMAIL && !!process.env.ALERTS_CRON_SECRET;
 const labels:Record<string,string>={pending:'En attente',sending:'Traitement en cours / à contrôler si bloqué',accepted:`Accepté par ${cfg.label}`,paused:`En pause chez ${cfg.label}`,failed:'Échec · à contrôler',uncertain:'Envoi incertain · vérifier avant relance',skipped:'Non envoyé : compte inactif / email absent'};
 return <section className="bg-paper border border-line rounded-xl p-5 space-y-3"><h2 className="font-semibold">Alertes par mail · suivi</h2><p className="text-sm">{enabled?`Envoi par ${cfg.label} configuré. Le déclenchement périodique doit également être actif.`:'Envoi désactivé ou configuration manquante. Consultez ACTIVER_ALERTES_V2.4.md dans le ZIP.'}</p><p className="text-sm text-mute">Planning et coordinateur : validation, affectation, changements de mission, démarrage, réalisation et annulation. Aucun mail client automatique. Un message accepté par le fournisseur n’est pas une preuve de livraison.</p>{error?<p className="text-sm text-ochre">Journal indisponible : appliquez v2_03_suivi_alertes.sql ou vérifiez la connexion.</p>:!data?.length?<p className="text-sm text-mute">Aucune alerte enregistrée. Les événements antérieurs à la migration ne sont pas réexpédiés.</p>:<div className="divide-y divide-line">{data.map((a:any)=><div key={a.id} className="py-3 text-sm"><p className="font-medium">{a.subject}</p><p className="text-xs text-mute mt-1">{a.recipient?.prenom} {a.recipient?.nom} · {new Date(a.created_at).toLocaleString('fr-FR')} · {labels[a.status]??a.status}</p>{a.last_error&&<p className="text-xs text-brick mt-1">{a.last_error}</p>}</div>)}</div>}</section>;
}
