import Link from 'next/link';
import { notFound } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { currentUser } from '@/lib/auth';
import { fmtDate, fmtHeure } from '@/lib/utils';
import { ETAT_LABEL, OP_ETAT_LABEL, type DemandeEtat, type OpEtat } from '@/lib/types';
import { PrintButton } from '@/components/print-button';
const executionTime = (s: string | null) => s ? new Date(s).toLocaleString('fr-FR', { timeZone: 'Europe/Paris', day:'2-digit', month:'2-digit', hour:'2-digit', minute:'2-digit' }) : '—';
export default async function Document({params}:{params:Promise<{id:string}>}) {
  const {id} = await params; const me = await currentUser();
  if (!me || me.role === 'chauffeur') notFound();
  const db = await createClient();
  const {data:d,error} = await db.from('demandes').select('*,client:clients(nom),operations(*,camion:camions(numero,immatriculation),equipiers:operation_equipiers(equipier:equipiers(prenom,nom)))').eq('id',id).single();
  if (error || !d) notFound();
  const ops = [...d.operations].sort((a:any,b:any) => (a.date_prevue ?? '').localeCompare(b.date_prevue ?? '') || a.ordre-b.ordre);
  return <div className="p-4 md:p-8 max-w-4xl mx-auto"><div className="no-print flex justify-between gap-3 mb-6"><Link href={`/demandes/${id}`}>← Retour à la demande</Link><PrintButton/></div><article className="mission-sheet bg-white border border-line rounded-xl p-6 md:p-10 space-y-6"><header className="flex justify-between gap-4 border-b border-line pb-5"><div><p className="text-xs tracking-widest">VULCAN FINE ART · ART TRANSIT INTL</p><h1 className="text-2xl font-semibold mt-3">Fiche de mission</h1><p>{d.numero} · {ETAT_LABEL[d.etat as DemandeEtat]}</p></div><p className="text-sm">{fmtDate(d.date_souhaitee)}<br/>{d.code_affaire && `Affaire ${d.code_affaire}`}</p></header><section><h2 className="font-semibold text-lg">{d.client?.nom ?? 'Client à préciser'}</h2><p>{d.contact_nom} {d.contact_telephone} {d.contact_email}</p></section><section className="grid grid-cols-2 gap-6"><div><h2 className="font-semibold">Enlèvement</h2><p className="whitespace-pre-line">{d.adresse_enlevement ?? 'À préciser'}</p></div><div><h2 className="font-semibold">Livraison</h2><p className="whitespace-pre-line">{d.adresse_livraison ?? 'À préciser'}</p></div></section><section><h2 className="font-semibold">Objets et consignes générales</h2><p className="whitespace-pre-line">{d.objets ?? 'À préciser'}</p><p>{d.nb_colis ?? '—'} colis · {d.volume_m3 ?? '—'} m³</p><p className="whitespace-pre-line mt-2">{d.observations}</p></section><section className="space-y-4"><h2 className="font-semibold">Déroulé des opérations</h2>{ops.length === 0 && <p>Aucune opération enregistrée.</p>}{ops.map((o:any) => <div key={o.id} className="mission-operation border border-line rounded-lg p-4 text-sm space-y-1"><h3 className="font-semibold">{o.libelle ?? o.type_operation} · {OP_ETAT_LABEL[o.etat as OpEtat]}</h3><p>{fmtDate(o.date_prevue)} · {fmtHeure(o.heure_debut)} · {o.duree_min ?? '—'} min</p><p className="whitespace-pre-line">{o.adresse}</p><p>Camion : {o.camion ? `${o.camion.numero} · ${o.camion.immatriculation ?? ''}` : 'Non affecté'}</p><p>Équipe : {o.equipiers.map((e:any) => [e.equipier?.prenom,e.equipier?.nom].filter(Boolean).join(' ')).join(', ') || 'Non affectée'}</p>{o.consignes && <p className="whitespace-pre-line">Consignes : {o.consignes}</p>}<p>Arrivée : {executionTime(o.heure_arrivee)} · Départ : {executionTime(o.heure_depart)}</p>{o.compte_rendu && <p className="whitespace-pre-line">Compte rendu : {o.compte_rendu}</p>}</div>)}</section><footer className="text-xs text-mute border-t border-line pt-3">Document interne · Vérifier les affectations et consignes avant le départ. Cette fiche ne constitue pas un devis ni une facture.</footer></article></div>;
}
