import Link from 'next/link';
import {EmailAlertsStatus} from '@/components/email-alerts-status';
export default function Integrations() {
  return <div className="p-4 md:p-8 max-w-5xl mx-auto space-y-6"><header><p className="text-xs uppercase tracking-widest text-mute">Documents et intégrations</p><h1 className="text-2xl font-semibold mt-1">Vos données, prêtes à servir</h1><p className="text-sm text-mute mt-2">Exportez les demandes, préparez une fiche de mission ou connectez un outil.</p></header><EmailAlertsStatus/><section className="bg-paper border border-line p-5 rounded-xl"><h2 className="font-semibold">Carte et itinéraires par camion</h2><p className="text-sm mt-2">{process.env.HERE_API_KEY ? "Service HERE configuré. Vérifiez les profils des véhicules dans Référentiels." : "À activer : ajouter HERE_API_KEY dans les variables serveur Vercel, puis renseigner les dimensions, le PTAC et les essieux de chaque camion."}</p><p className="text-sm text-mute mt-2">La migration SQL v2_02 doit être appliquée avant d’utiliser les adresses structurées et la nouvelle planification.</p></section><div className="grid md:grid-cols-3 gap-4">{[
    {title:'Tableau de suivi',text:'Filtrez par client, date ou état, puis téléchargez la page en CSV compatible Excel.',href:'/demandes',action:'Choisir les demandes'},
    {title:'Fiche de mission',text:'Depuis chaque demande : adresses, consignes, opérations, camion et équipe. Impression A4 ou PDF depuis le navigateur.',href:'/demandes',action:'Ouvrir une demande'},
    {title:'API documentée',text:'Récupérez les demandes et leur détail en JSON. Le contrat OpenAPI est importable dans Postman.',href:'/api/v1/openapi',action:'Télécharger OpenAPI'},
  ].map(c=><section key={c.title} className="bg-paper border border-line rounded-xl p-5 flex flex-col"><h2 className="font-semibold">{c.title}</h2><p className="text-sm text-mute my-3 flex-1">{c.text}</p><a className="text-sm text-cobalt-ink font-medium" href={c.href}>{c.action} →</a></section>)}</div><section className="bg-paper border border-line rounded-xl p-5 space-y-4"><h2 className="font-semibold">Brancher un outil externe</h2><p className="text-sm">L’API accepte un jeton utilisateur Supabase (<code>access_token</code>) dans l’en-tête <code>Authorization: Bearer …</code>. Le compte doit être actif et disposer d’un rôle métier autorisé. Les cookies fonctionnent depuis cette application.</p><pre className="overflow-auto rounded-lg bg-ink text-white p-4 text-xs">{`curl "$CAMIONNAGE_URL/api/v1/demandes?f=actives&limit=50&page=1" \\\n  -H "Authorization: Bearer $SUPABASE_ACCESS_TOKEN"`}</pre><p className="text-sm">La réponse contient <code>data</code> et <code>pagination</code>. Incrémentez <code>page</code> tant que <code>has_more</code> vaut <code>true</code>. Pour une mission complète : <code>GET /api/v1/demandes/&#123;id&#125;</code>.</p><p className="text-sm text-mute">Cette version propose une API de lecture. Les exports CSV portent sur la page affichée. Les jetons expirent : leur renouvellement relève de votre intégration. Aucune synchronisation Akanea, aucun webhook, devis ou facture automatique n’est activé.</p><Link href="/planning" className="text-sm text-cobalt-ink inline-block">Revenir au planning →</Link></section></div>;
}
